server:
  port: 8091

# ===================================================================
# Spring 核心配置
# ===================================================================
spring:
  application:
    name: xuele-group-buy
  threads:
    virtual:
      enabled: true
  # 1. Redis 配置
  data:
    redis:
      host: 10.0.0.1
      port: 16379
      database: 0
      timeout: 10000ms

  # 2. 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.1:13306/group_buy_market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5             # 最小空闲连接
      maximum-pool-size: 20       # 最大连接数
      idle-timeout: 180000        # 空闲存活时间 (3分钟)
      max-lifetime: 1800000       # 连接最大生命周期 (30分钟)
      connection-timeout: 30000   # 连接超时 (30秒)
      auto-commit: true
      connection-test-query: SELECT 1

# ===================================================================
# Mybatis 配置
# ===================================================================
mybatis:
  # 请确保你的 XML 文件真的在 resources/mybatis/mapper 目录下
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

# ===================================================================
# 自定义线程池配置 (注意：这需要你代码里有对应的 @ConfigurationProperties 读取类)
# ===================================================================
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ===================================================================
# 日志配置
# ===================================================================
logging:
  level:
    root: info
    # 建议开启你自己的包的 Debug 日志，方便调试 SQL
    cn.xuele: debug
  config: classpath:logback-spring.xml


# ===================================================================
# 自定义 redis 配置
# ===================================================================
redis:
  sdk:
    config:
      host: 10.0.0.1
      port: 16379
      poolSize: 64
      minIdleSize: 10
      idleTimeout: 10000
      connectTimeout: 10000
      retryAttempts: 3
      retryInterval: 1000
      pingInterval: 0
      keepAlive: true