server:
  port: ${TAG_SERVER_PORT:8101}

spring:
  application:
    name: xuele-group-buy-tag-service

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: tri
    port: ${DUBBO_PROTOCOL_PORT:-1}
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:nacos://124.221.233.121:8848}
  scan:
    base-packages: cn.xuele.tag.trigger.rpc


  management:
    endpoints:
      web:
        exposure:
          include: health,info
